micronaut:
  application:
    name: loan-application-ETL-service
  server:
    port: 8095

oracle:
  className: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@10.5.129.98:1653/MULEASSETPT
  username: EDU_LOAN_USER
  password: IDfc$#2021
  initialSize: 1
  maxActive: 50
  minIdle: 20

aerospike:
  namespace: edu_loan_ops
  host: 10.180.15.130,10.180.15.131,10.180.15.132
  port: 3000,3000,3000
  username: eduw
  password: eduw
  user:
    authentication:
      enabled: 1
  rwPolicy:
    readPolicyDefault:
      totalTimeout: 1000
    writePolicyDefault:
      totalTimeout: 500
    minConnsPerNode: 20
    maxSocketIdle: 60
  expiration:
    ttl: 6000

kafka:
  server:
    key: bootstrap.servers
    value: 10.180.11.77:9092,10.180.11.78:9092,10.180.11.43:9092
  max:
    poll:
      records: 200
      interval:
        ms: 60000
  consumer:
    poll:
      interval: 500
    thread:
      count: 2
    partitionCount: 2
  offset:
    poll:
      interval: 30000
  topic:
    t1: stage-workflow-kafka-topic
    t2: internal-update-kafka-topic
    t3: integration-router-kafka-topic
    t4: etl-kafka-topic

io:
  core:
    pool:
      size: 10
  max:
    pool:
      size: 20
  keep:
    alive:
      time: 1000


